FROM php:8.1-apache

RUN docker-php-ext-install mysqli pdo pdo_mysql && docker-php-ext-enable pdo_mysql

#RUN chown -R root:root /bin/bash

COPY 000-default.conf /etc/apache2/sites-available/000-default.conf
RUN a2enmod rewrite

WORKDIR /var/www/public
#USER root

COPY php.ini /usr/local/etc/php/php.ini
#COPY phpext/* /usr/local/etc/php/phpext/

COPY src /var/www/public
RUN chown -R www-data:www-data /var/www/public

CMD ["apache2-foreground"]




